# How to create replicas without repeating the services name
version: '3.5'
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: app
    ports:
      - "80:80"
    networks:
      - app_network
  app_1:
    build: ./app
    image: app
    container_name: app_1
    networks:
      - app_network
  app_2:
    build: ./app
    image: app
    container_name: app_2
    networks:
      - app_network
  app_3:
    build: ./app
    image: app
    container_name: app_3
    networks:
      - app_network

networks:
  app_network:
    name: app_network